<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="5" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-03-14T11:25:34 AEST" name="Default suite" finished-at="2021-03-14T11:26:39 AEST" duration-ms="65065">
    <groups>
    </groups>
    <test started-at="2021-03-14T11:25:34 AEST" name="Default test" finished-at="2021-03-14T11:26:39 AEST" duration-ms="65065">
      <class name="cattest.tests.TestAPI">
        <test-method is-config="true" signature="setup()[pri:0, instance:cattest.tests.TestAPI@68c72235]" started-at="2021-03-14T11:25:34 AEST" name="setup" finished-at="2021-03-14T11:25:34 AEST" duration-ms="120" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="isInValidFactsHTTPStatusCode()[pri:1, instance:cattest.tests.TestAPI@68c72235]" started-at="2021-03-14T11:25:34 AEST" name="isInValidFactsHTTPStatusCode" finished-at="2021-03-14T11:25:37 AEST" duration-ms="2528" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isInValidFactsHTTPStatusCode -->
        <test-method signature="isInValidFactsIdHTTPStatusCode()[pri:1, instance:cattest.tests.TestAPI@68c72235]" started-at="2021-03-14T11:25:37 AEST" name="isInValidFactsIdHTTPStatusCode" finished-at="2021-03-14T11:25:38 AEST" duration-ms="1187" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isInValidFactsIdHTTPStatusCode -->
        <test-method signature="isValidFactsHTTPStatusCode()[pri:1, instance:cattest.tests.TestAPI@68c72235]" started-at="2021-03-14T11:25:38 AEST" name="isValidFactsHTTPStatusCode" finished-at="2021-03-14T11:25:39 AEST" duration-ms="1199" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isValidFactsHTTPStatusCode -->
        <test-method signature="isValidFactsIdHTTPStatusCode()[pri:1, instance:cattest.tests.TestAPI@68c72235]" started-at="2021-03-14T11:25:39 AEST" name="isValidFactsIdHTTPStatusCode" finished-at="2021-03-14T11:25:40 AEST" duration-ms="1202" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isValidFactsIdHTTPStatusCode -->
        <test-method signature="isAllFactsIdValid()[pri:2, instance:cattest.tests.TestAPI@68c72235]" started-at="2021-03-14T11:25:40 AEST" name="isAllFactsIdValid" finished-at="2021-03-14T11:26:35 AEST" duration-ms="54650" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at org.testng.Assert.assertEquals(Assert.java:761)
at cattest.tests.TestAPI.isAllFactsIdValid(TestAPI.java:129)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isAllFactsIdValid -->
        <test-method signature="isFactsAllValid()[pri:2, instance:cattest.tests.TestAPI@68c72235]" started-at="2021-03-14T11:26:35 AEST" name="isFactsAllValid" finished-at="2021-03-14T11:26:37 AEST" duration-ms="2236" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at org.testng.Assert.assertEquals(Assert.java:761)
at cattest.tests.TestAPI.isFactsAllValid(TestAPI.java:113)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isFactsAllValid -->
        <test-method signature="isJSOnStructureCorrect()[pri:2, instance:cattest.tests.TestAPI@68c72235]" started-at="2021-03-14T11:26:37 AEST" name="isJSOnStructureCorrect" finished-at="2021-03-14T11:26:39 AEST" duration-ms="1900" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isJSOnStructureCorrect -->
      </class> <!-- cattest.tests.TestAPI -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
